# Welcome to Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr[0,3]

7

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]

6

In [9]:
myarr[0, 1] = 45

In [10]:
myarr

array([[ 3, 45, 37,  7]])

# Array creation: conversion fromother python structure

In [13]:
listarray = np.array([[1,2,3],[3,4,5],[6,7,8]])

In [14]:
listarray

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
listarray.dtype

dtype('int64')

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({34,25,36})

array({25, 34, 36}, dtype=object)

In [19]:
zeros = np.zeros((3,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,5,4)

In [26]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [27]:
emp = np.empty((4,6))

In [28]:
emp

array([[0.00000000e+000, 2.46151513e-312, 2.41907520e-312,
        2.05833592e-312, 6.79038654e-313, 6.79038653e-313],
       [2.37663529e-312, 2.05833592e-312, 2.41907520e-312,
        1.93101617e-312, 9.33678148e-313, 9.33678148e-313],
       [1.97345609e-312, 1.93101617e-312, 9.33678148e-313,
        9.33678148e-313, 1.97345609e-312, 1.93101617e-312],
       [9.33678148e-313, 9.33678148e-313, 1.97345609e-312,
        2.02566915e-322, 0.00000000e+000, 0.00000000e+000]])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [31]:
 ide = np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
ide.shape

(45, 45)

In [35]:
arr = np.arange(0,99)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr = arr.ravel()

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr.shape

(99,)